apiVersion: v1
kind: Namespace
metadata:
  name: frontend
  labels:
    app.kubernetes.io/part-of: su-devops-lokesh26
    linkerd.io/inject: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: backend-users
  labels:
    app.kubernetes.io/part-of: su-devops-lokesh26
    linkerd.io/inject: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: backend-products
  labels:
    app.kubernetes.io/part-of: su-devops-lokesh26
    linkerd.io/inject: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: backend-orders
  labels:
    app.kubernetes.io/part-of: su-devops-lokesh26
    linkerd.io/inject: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: database
  labels:
    app.kubernetes.io/part-of: su-devops-lokesh26
---
apiVersion: v1
kind: Namespace
metadata:
  name: api-gateway
  labels:
    app.kubernetes.io/part-of: su-devops-lokesh26
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    app.kubernetes.io/part-of: su-devops-lokesh26
---
apiVersion: v1
kind: Namespace
metadata:
  name: logging
  labels:
    app.kubernetes.io/part-of: su-devops-lokesh26
---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  labels:
    app.kubernetes.io/part-of: su-devops-lokesh26
---
apiVersion: v1
kind: Namespace
metadata:
  name: sealed-secrets
  labels:
    app.kubernetes.io/part-of: su-devops-lokesh26
---
apiVersion: v1
kind: Namespace
metadata:
  name: security
  labels:
    app.kubernetes.io/part-of: su-devops-lokesh26
